export const WORDS_EN: readonly string[] = [
  'time', 'play', 'game', 'rain', 'hill', 'door', 'tree', 'leaf', 'salt', 'milk',
  'rice', 'fish', 'star', 'moon', 'blue', 'slow', 'tall', 'lazy', 'snow', 'cake',
  'song', 'book', 'kite', 'frog', 'bear', 'lion', 'wolf', 'duck', 'gold',
  'bored', 'happy', 'smile', 'laugh', 'dream', 'cloud', 'sunny', 'storm', 'river',
  'ocean', 'beach', 'house', 'table', 'chair', 'apple', 'sugar', 'sweet', 'spicy',
  'water', 'juice', 'horse', 'tiger', 'zebra', 'panda', 'mouse', 'snake', 'eagle',
  'robot', 'light', 'night', 'lunch', 'snack', 'candy', 'music', 'dance', 'paint',
  'color', 'green', 'black', 'white', 'quick', 'small', 'large', 'short', 'cheap',
  'funny', 'brave', 'smart', 'money', 'paper', 'shoes', 'shirt', 'pants', 'magic',
  'pizza', 'train', 'plane',
  'window', 'garden', 'flower', 'cheese', 'rocket', 'planet', 'dinner', 'friend',
  'school', 'office', 'market', 'pencil', 'jacket', 'winter', 'summer', 'spring',
  'autumn', 'puzzle', 'riddle', 'secret', 'wizard', 'dragon', 'castle', 'bridge',
  'street', 'corner', 'pocket', 'button', 'banana', 'monkey', 'rabbit', 'turtle',
  'cookie', 'guitar', 'purple', 'orange', 'yellow',
  'morning', 'chicken', 'penguin', 'rainbow', 'bicycle', 'picture', 'teacher',
  'weather', 'holiday', 'diamond', 'unicorn', 'monster',
];
