export const townId = {
  'town.eyebrow': 'DIORAMA KOTA PESISIR',
  'town.title': 'Kota yang tak pernah diam.',
  'town.intro': 'Putar waktu. Ubah langit. Lihat satu kota menghadapi hari biasa hingga bencana.',
  'town.controls': 'Atur dunia',
  'town.closeControls': 'Tutup pengaturan',
  'town.reset': 'Atur ulang',
  'town.play': 'Jalankan waktu',
  'town.pause': 'Jeda waktu',
  'town.time': 'Waktu',
  'town.camera': 'Kamera',
  'town.orbitLeft': 'Putar ke kiri',
  'town.orbitRight': 'Putar ke kanan',
  'town.zoomIn': 'Perbesar',
  'town.zoomOut': 'Perkecil',
  'town.weather': 'Cuaca',
  'town.disaster': 'Bencana',
  'town.season': 'Musim',
  'town.climate': 'Iklim',
  'town.now': 'Kondisi sekarang',
  'town.live': 'KOTA HIDUP',
  'town.paused': 'WAKTU DIJEDA',
  'town.gesture': 'Seret: putar · Shift+seret/dua jari: geser · gulir/cubit: zoom',
  'town.loading': 'Membangun kota…',
  'town.error': 'Tampilan 3D gagal dimuat di perangkat ini.',
  'town.visualNote': 'Simulasi visual. Dampak dan skala kejadian disederhanakan.',
  'town.activity': 'Aktivitas',
  'town.activity.busy': 'Jalanan ramai, warga beraktivitas.',
  'town.activity.quiet': 'Kota melambat di malam hari.',
  'town.activity.shelter': 'Warga mencari tempat aman.',
  'town.activity.weather': 'Aktivitas luar ruang berkurang.',
  'town.weather.clear': 'Cerah',
  'town.weather.cloudy': 'Berawan',
  'town.weather.rain': 'Hujan',
  'town.weather.storm': 'Badai',
  'town.weather.snow': 'Salju',
  'town.weather.fog': 'Kabut',
  'town.weather.heat': 'Gelombang panas',
  'town.disaster.none': 'Tidak ada',
  'town.disaster.flood': 'Banjir',
  'town.disaster.earthquake': 'Gempa',
  'town.disaster.wildfire': 'Kebakaran lahan',
  'town.disaster.tsunami': 'Tsunami',
  'town.disaster.tornado': 'Tornado',
  'town.season.spring': 'Semi',
  'town.season.summer': 'Panas',
  'town.season.autumn': 'Gugur',
  'town.season.winter': 'Dingin',
  'town.climate.temperate': 'Sedang',
  'town.climate.tropical': 'Tropis',
  'town.climate.arid': 'Kering',
} as const;

export const townEn: Record<keyof typeof townId, string> = {
  'town.eyebrow': 'COASTAL CITY DIORAMA',
  'town.title': 'A city that never stands still.',
  'town.intro': 'Turn the clock. Change the sky. Watch one city face ordinary days and disasters.',
  'town.controls': 'Shape the world',
  'town.closeControls': 'Close controls',
  'town.reset': 'Reset',
  'town.play': 'Play time',
  'town.pause': 'Pause time',
  'town.time': 'Time',
  'town.camera': 'Camera',
  'town.orbitLeft': 'Rotate left',
  'town.orbitRight': 'Rotate right',
  'town.zoomIn': 'Zoom in',
  'town.zoomOut': 'Zoom out',
  'town.weather': 'Weather',
  'town.disaster': 'Disaster',
  'town.season': 'Season',
  'town.climate': 'Climate',
  'town.now': 'Current conditions',
  'town.live': 'CITY IN MOTION',
  'town.paused': 'TIME PAUSED',
  'town.gesture': 'Drag: orbit · Shift+drag/two fingers: pan · scroll/pinch: zoom',
  'town.loading': 'Building the city…',
  'town.error': 'The 3D view could not load on this device.',
  'town.visualNote': 'Visual simulation. Event scale and effects are simplified.',
  'town.activity': 'Activity',
  'town.activity.busy': 'Traffic flows and residents go about their day.',
  'town.activity.quiet': 'The city slows down at night.',
  'town.activity.shelter': 'Residents seek safer ground.',
  'town.activity.weather': 'Outdoor activity slows down.',
  'town.weather.clear': 'Clear',
  'town.weather.cloudy': 'Cloudy',
  'town.weather.rain': 'Rain',
  'town.weather.storm': 'Storm',
  'town.weather.snow': 'Snow',
  'town.weather.fog': 'Fog',
  'town.weather.heat': 'Heatwave',
  'town.disaster.none': 'None',
  'town.disaster.flood': 'Flood',
  'town.disaster.earthquake': 'Earthquake',
  'town.disaster.wildfire': 'Wildfire',
  'town.disaster.tsunami': 'Tsunami',
  'town.disaster.tornado': 'Tornado',
  'town.season.spring': 'Spring',
  'town.season.summer': 'Summer',
  'town.season.autumn': 'Autumn',
  'town.season.winter': 'Winter',
  'town.climate.temperate': 'Temperate',
  'town.climate.tropical': 'Tropical',
  'town.climate.arid': 'Arid',
};
