export const townId = {
  'town.eyebrow': 'DIORAMA KOTA PESISIR',
  'town.title': 'Kota yang tak pernah diam.',
  'town.intro': 'Putar waktu. Ubah langit. Lihat satu kota menghadapi hari biasa hingga bencana.',
  'town.controls': 'Atur dunia',
  'town.closeControls': 'Tutup pengaturan',
  'town.reset': 'Atur ulang',
  'town.play': 'Jalankan waktu',
  'town.pause': 'Jeda waktu',
  'town.time': 'Waktu',
  'town.camera': 'Kamera',
  'town.orbitLeft': 'Putar ke kiri',
  'town.orbitRight': 'Putar ke kanan',
  'town.zoomIn': 'Perbesar',
  'town.zoomOut': 'Perkecil',
  'town.weather': 'Cuaca',
  'town.disaster': 'Bencana',
  'town.season': 'Musim',
  'town.climate': 'Iklim',
  'town.now': 'Kondisi sekarang',
  'town.live': 'KOTA HIDUP',
  'town.paused': 'WAKTU DIJEDA',
  'town.gesture': 'WASD: jelajah · seret kiri: putar 360° · Shift/dua jari: geser · gulir/cubit: zoom',
  'town.viewport': 'Kota 3D interaktif. WASD untuk menjelajah, seret kiri untuk memutar kamera.',
  'town.timeNote': 'Jam hanya mengatur cahaya. Kendaraan, warga dan cuaca tetap bergerak saat waktu dijeda.',
  'town.eventNote': 'Bencana tumbuh, mencapai puncak, lalu mereda. Tidak ada menghentikan kejadian; bekas kerusakan tetap ada sampai Pulihkan kota.',
  'town.repair': 'Pulihkan kota',
  'town.phase.onset': 'Proses: kejadian mulai berkembang.',
  'town.phase.peak': 'Proses: bencana berlangsung, dampak bertambah.',
  'town.phase.aftermath': 'Setelah kejadian: bahaya mereda, bekas kerusakan tetap terlihat.',
  'town.eventPreview': 'Pratinjau kejadian',
  'town.eventStart': 'Awal',
  'town.eventPeak': 'Puncak',
  'town.eventLater': 'Setelah kejadian',
  'town.moveForward': 'Jelajah maju · W',
  'town.moveBack': 'Jelajah mundur · S',
  'town.moveLeft': 'Jelajah ke kiri · A',
  'town.moveRight': 'Jelajah ke kanan · D',
  'town.speed': 'Kecepatan aktivitas',
  'town.explore': 'Jelajahi kota',
  'town.explore.downtown': 'Pusat kota',
  'town.explore.river': 'Tepi sungai',
  'town.explore.beach': 'Pantai & dermaga',
  'town.explore.station': 'Stasiun',
  'town.explore.park': 'Taman',
  'town.explore.hills': 'Perbukitan',
  'town.loading': 'Membangun kota…',
  'town.error': 'Tampilan 3D gagal dimuat di perangkat ini.',
  'town.visualNote': 'Simulasi visual. Dampak dan skala kejadian disederhanakan.',
  'town.activity': 'Aktivitas',
  'town.activity.busy': 'Jalanan ramai, warga beraktivitas.',
  'town.activity.quiet': 'Kota melambat di malam hari.',
  'town.activity.shelter': 'Warga mencari tempat aman.',
  'town.activity.recovery': 'Bahaya mereda. Kota perlu dipulihkan.',
  'town.activity.weather': 'Aktivitas luar ruang berkurang.',
  'town.weather.clear': 'Cerah',
  'town.weather.cloudy': 'Berawan',
  'town.weather.rain': 'Hujan',
  'town.weather.storm': 'Badai',
  'town.weather.lightning': 'Kilat',
  'town.weather.blizzard': 'Badai salju',
  'town.weather.snow': 'Salju',
  'town.weather.fog': 'Kabut',
  'town.weather.heat': 'Gelombang panas',
  'town.disaster.none': 'Tidak ada',
  'town.disaster.flood': 'Banjir',
  'town.disaster.earthquake': 'Gempa',
  'town.disaster.wildfire': 'Kebakaran lahan',
  'town.disaster.tsunami': 'Tsunami',
  'town.disaster.tornado': 'Tornado',
  'town.disaster.hailstorm': 'Hujan es',
  'town.disaster.landslide': 'Longsor',
  'town.disaster.drought': 'Kekeringan',
  'town.season.spring': 'Semi',
  'town.season.summer': 'Panas',
  'town.season.autumn': 'Gugur',
  'town.season.winter': 'Dingin',
  'town.climate.temperate': 'Sedang',
  'town.climate.tropical': 'Tropis',
  'town.climate.arid': 'Kering',
} as const;

export const townEn: Record<keyof typeof townId, string> = {
  'town.eyebrow': 'COASTAL CITY DIORAMA',
  'town.title': 'A city that never stands still.',
  'town.intro': 'Turn the clock. Change the sky. Watch one city face ordinary days and disasters.',
  'town.controls': 'Shape the world',
  'town.closeControls': 'Close controls',
  'town.reset': 'Reset',
  'town.play': 'Play time',
  'town.pause': 'Pause time',
  'town.time': 'Time',
  'town.camera': 'Camera',
  'town.orbitLeft': 'Rotate left',
  'town.orbitRight': 'Rotate right',
  'town.zoomIn': 'Zoom in',
  'town.zoomOut': 'Zoom out',
  'town.weather': 'Weather',
  'town.disaster': 'Disaster',
  'town.season': 'Season',
  'town.climate': 'Climate',
  'town.now': 'Current conditions',
  'town.live': 'CITY IN MOTION',
  'town.paused': 'TIME PAUSED',
  'town.gesture': 'WASD: explore · left drag: orbit 360° · Shift/two fingers: pan · scroll/pinch: zoom',
  'town.viewport': 'Interactive 3D city. WASD to explore, left drag to orbit the camera.',
  'town.timeNote': 'The clock only controls lighting. Traffic, residents and weather keep moving when time is paused.',
  'town.eventNote': 'Disasters build, peak and subside. None stops the event; damage remains until you Restore city.',
  'town.repair': 'Restore city',
  'town.phase.onset': 'Onset: the event is developing.',
  'town.phase.peak': 'In progress: hazards are active and impacts are building.',
  'town.phase.aftermath': 'Aftermath: hazards subside, visible damage remains.',
  'town.eventPreview': 'Event preview',
  'town.eventStart': 'Onset',
  'town.eventPeak': 'Peak',
  'town.eventLater': 'Aftermath',
  'town.moveForward': 'Explore forward · W',
  'town.moveBack': 'Explore backward · S',
  'town.moveLeft': 'Explore left · A',
  'town.moveRight': 'Explore right · D',
  'town.speed': 'Activity speed',
  'town.explore': 'Explore the city',
  'town.explore.downtown': 'City center',
  'town.explore.river': 'Riverfront',
  'town.explore.beach': 'Beach & pier',
  'town.explore.station': 'Station',
  'town.explore.park': 'Park',
  'town.explore.hills': 'Hills',
  'town.loading': 'Building the city…',
  'town.error': 'The 3D view could not load on this device.',
  'town.visualNote': 'Visual simulation. Event scale and effects are simplified.',
  'town.activity': 'Activity',
  'town.activity.busy': 'Traffic flows and residents go about their day.',
  'town.activity.quiet': 'The city slows down at night.',
  'town.activity.shelter': 'Residents seek safer ground.',
  'town.activity.recovery': 'Hazards subside. The city needs restoration.',
  'town.activity.weather': 'Outdoor activity slows down.',
  'town.weather.clear': 'Clear',
  'town.weather.cloudy': 'Cloudy',
  'town.weather.rain': 'Rain',
  'town.weather.storm': 'Storm',
  'town.weather.lightning': 'Lightning',
  'town.weather.blizzard': 'Blizzard',
  'town.weather.snow': 'Snow',
  'town.weather.fog': 'Fog',
  'town.weather.heat': 'Heatwave',
  'town.disaster.none': 'None',
  'town.disaster.flood': 'Flood',
  'town.disaster.earthquake': 'Earthquake',
  'town.disaster.wildfire': 'Wildfire',
  'town.disaster.tsunami': 'Tsunami',
  'town.disaster.tornado': 'Tornado',
  'town.disaster.hailstorm': 'Hailstorm',
  'town.disaster.landslide': 'Landslide',
  'town.disaster.drought': 'Drought',
  'town.season.spring': 'Spring',
  'town.season.summer': 'Summer',
  'town.season.autumn': 'Autumn',
  'town.season.winter': 'Winter',
  'town.climate.temperate': 'Temperate',
  'town.climate.tropical': 'Tropical',
  'town.climate.arid': 'Arid',
};
