export const seoCopy = {
  id: {
    'seo.home.title': 'Mini Game Browser untuk Gabut',
    'seo.home.description': 'Main mini game cepat di browser saat lagi gabut. Pilih permainan refleks, puzzle, balapan, dan petualangan tanpa akun.',
    'seo.home.heading': 'Mini game browser untuk mengisi waktu gabut',
    'seo.daily.title': 'Daily Gauntlet: Tantangan Mini Game Harian',
    'seo.daily.description': 'Hadapi lima mini game dalam Daily Gauntlet harian. Urutan permainan sama untuk semua pemain dan langsung bisa dimainkan di browser.',
    'seo.daily.heading': 'Daily Gauntlet mini game harian',
    'seo.education.title': 'Education Interaktif tentang Bumi dan Atmosfer',
    'seo.education.description': 'Jelajahi fakta interaktif tentang lapisan Bumi dan atmosfer, lengkap dengan perbandingan mudah dipahami serta sumber tepercaya.',
    'seo.education.heading': 'Eksplorasi interaktif Bumi dan atmosfer',
    'seo.below.title': 'Below the Surface: Jelajah Lapisan Bumi',
    'seo.below.description': 'Telusuri perjalanan dari permukaan, tanah, air tanah, kerak, mantel, hingga inti Bumi melalui fakta dan sumber ilmiah.',
    'seo.below.heading': 'Below the Surface',
    'seo.above.title': 'Above the Surface: Jelajah Lapisan Atmosfer',
    'seo.above.description': 'Naik dari permukaan Bumi melewati troposfer hingga eksosfer dengan fakta interaktif dan sumber NASA.',
    'seo.above.heading': 'Above the Surface',
    'seo.weird.title': 'Weird Cabinet: Anti-Game untuk Saat Gabut',
    'seo.weird.description': 'Coba Oracle Gabut, Tombol Tidak Berguna, Dadu Mood, Skala Gabut, dan Biro Izin Tidak Produktif: lima interaksi kecil tanpa akun atau penyimpanan.',
    'seo.weird.heading': 'Weird Cabinet',
    'seo.game.titleSuffix': 'Game browser',
    'seo.game.descriptionPrefix': 'Mainkan',
    'seo.game.descriptionSuffix': 'Main langsung di browser tanpa akun atau instalasi.',
    'seo.game.headingSuffix': 'mini game browser',
    'seo.notFound.title': 'Halaman tidak ditemukan',
    'seo.notFound.description': 'Halaman ini tidak tersedia di ihavenothingtodo.',
    'seo.placeholder.title': 'Halaman belum tersedia',
    'seo.placeholder.description': 'Halaman ini belum tersedia di ihavenothingtodo.',
  },
  en: {
    'seo.home.title': 'Quick Browser Games for a Break',
    'seo.home.description': 'Play quick browser games when you have a spare moment. Pick reflex, puzzle, racing, and adventure games with no account required.',
    'seo.home.heading': 'Quick browser games for a spare moment',
    'seo.daily.title': 'Daily Gauntlet: Daily Mini-Game Challenge',
    'seo.daily.description': 'Take on five mini-games in the Daily Gauntlet. Everyone gets the same lineup each day and can play directly in the browser.',
    'seo.daily.heading': 'Daily mini-game gauntlet',
    'seo.education.title': 'Interactive Education about Earth and Atmosphere',
    'seo.education.description': 'Explore interactive facts about Earth layers and the atmosphere, with easy-to-follow comparisons and trustworthy sources.',
    'seo.education.heading': 'Interactive Earth and atmosphere exploration',
    'seo.below.title': 'Below the Surface: Explore Earth Layers',
    'seo.below.description': 'Travel from the surface through soil, groundwater, crust, mantle, and toward Earth’s core with facts and scientific sources.',
    'seo.below.heading': 'Below the Surface',
    'seo.above.title': 'Above the Surface: Explore Atmospheric Layers',
    'seo.above.description': 'Travel from Earth’s surface through the troposphere to the exosphere with interactive facts and NASA sources.',
    'seo.above.heading': 'Above the Surface',
    'seo.weird.title': 'Weird Cabinet: Anti-Games for a Break',
    'seo.weird.description': 'Try the Boredom Oracle, Useless Button, Mood Dice, Boredom Scale, and Department of Unproductive Permission: five tiny interactions with no account or saved data.',
    'seo.weird.heading': 'Weird Cabinet',
    'seo.game.titleSuffix': 'Browser game',
    'seo.game.descriptionPrefix': 'Play',
    'seo.game.descriptionSuffix': 'Play it directly in your browser with no account or installation.',
    'seo.game.headingSuffix': 'browser mini-game',
    'seo.notFound.title': 'Page not found',
    'seo.notFound.description': 'This page is not available on ihavenothingtodo.',
    'seo.placeholder.title': 'Page not available yet',
    'seo.placeholder.description': 'This page is not available yet on ihavenothingtodo.',
  },
} as const;

export type SeoCopyKey = keyof typeof seoCopy.id;
